 function [roomfreddy,roombonnie,roomchica, freddyLocation, ...
    bonnieLocation, chicaLocation, cycle1, cycle2, ...
    initialMove] = fnafv7 ...
    ...
    (leftdoor, rightdoor, ...
    freddyLocation, bonnieLocation, chicaLocation, ...
    camera, ...
    cycle1, cycle2, ...
    initialMove, ...
    AIlevelFreddy, AIlevelBonnie, AIlevelChica)

% Create an array of room names for easier access 
room = ["Show stage";"Dinning Area";"Pirate Cove";"West Hall";"West Hall Corner";
    "Supply Closet";"East Hall";"East Hall Corner";"Backstage";"Kitchen";"Restroom";"Doorway";"Office"];

% Run function for Freddy
[roomfreddy, cycle2, freddyLocation] = freddy (AIlevelFreddy, rightdoor, ...
    camera, freddyLocation, cycle2, room);

% Run function for Chica and Bonnie
[roombonnie, roomchica, cycle1, bonnieLocation, chicaLocation, initialMove] = bonniechica (bonnieLocation, ...
    initialMove, AIlevelBonnie, rightdoor, leftdoor, chicaLocation, ...
    AIlevelChica, cycle1, room);

 end